---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: springboot-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spboot_postgres
    spec:
      containers:
      - name: postgresdb
        image: postgres:latest
        ports:
        - name: postgresdb-port
          containerPort: 5432
        volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/ddata
      - name: springbootapp
        image: naveenkrishiv/springbootcrud
        ports:
          - name: spboot-port
            containerPort: 36000

      volumes:
        - name: psql-data
             
