apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - name: postgresdb-port
          containerPort: 5432
      volumeMounts:
          - name: psql-data
            mountPath: /var/lib/postgresql/data
  volumes:
      - name: psql-data